; AddVariables.asm - Chapter 3 example.

COMMENT !
Modify the AddVariables program so it uses 64-bit variables. 
Describe the syntax errors generated by the assembler and 
what steps you took to resolve the errors.
!

ExitProcess PROTO	;No parameters when using the PROTO keyword

.data
;change DWORD to QWORD
firstval QWORD 20002000h
secondval QWORD 11111111h
thirdval QWORD 22222222h
sum QWORD 0

.code
main PROC
	;use rax instead of eax because rax is the 64-bit version
	mov rax, firstval
	add rax, secondval
	add rax, thirdval
	mov sum, rax

	call ExitProcess ;INVOKE isn't supported so use call instead
main ENDP
END main
